# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='tag',
            field=models.CharField(default='', max_length=20),
        ),
    ]
